account/urls.py
from django.contrib.auth import views
from django.urls import path
from .views import ProductList, ProductGallery, ProductCreator, ProductCreatorGallery, ProductCreatorUpdate, \
    ProductCreatorGalleryUpdate, ProductDeleteView, ProductGalleryDeleteView, user_register, Profile

app_name = 'account'
urlpatterns = [
    path('login/', views.LoginView.as_view(), name='login'),
    path('register/', user_register, name='register'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('profile/', Profile.as_view(), name="profile"),
    #
    # path('password_change/', views.PasswordChangeView.as_view(), name='password_change'),
    # path('password_change/done/', views.PasswordChangeDoneView.as_view(), name='password_change_done'),
    #
    # path('password_reset/', views.PasswordResetView.as_view(), name='password_reset'),
    # path('password_reset/done/', views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    # path('reset/<uidb64>/<token>/', views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    # path('reset/done/', views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]
urlpatterns += [
    path('', ProductList.as_view(), name='home'),
    path('gallery/', ProductGallery.as_view(), name='gallery'),
    path('product/create', ProductCreator.as_view(), name='productcreator'),
    path('product/create/<int:pk>', ProductCreatorUpdate.as_view(), name='productupdate'),
    path('product/create/gallery', ProductCreatorGallery.as_view(), name='productcreatorgallery'),
    path('product/create/gallery/<int:pk>', ProductCreatorGalleryUpdate.as_view(), name='productgalleryupdate'),
    path('product/delete/<int:pk>', ProductDeleteView.as_view(), name='productdelete'),
    path('product/delete/gallery/<int:pk>', ProductGalleryDeleteView.as_view(), name='productgallerydelete'),
]

djangoecommerce/urls.py
from django.conf.urls.static import static

from djangoecommerce import settings
from django.contrib import admin
from django.urls import path, include, re_path


urlpatterns = [
    path('', include('eshop_home.urls')),
    path('', include('eshop_products.urls')),
    path('', include('eshop_settings.urls')),
    path('', include('products_order.urls')),
    path('comment/', include('comment.urls')),
    re_path(r'^ratings/', include('star_ratings.urls', namespace='ratings')),
    path('account/', include('account.urls')),
    path('admin/', admin.site.urls),

]

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products_order/urls.py
from django.urls import path
from .views import *

app_name = 'user-order'
urlpatterns = [
    path('add-user-order', add_user_order, name='add-user-order'),
    path('open_order', user_open_order, name='user_open_order'),
    path('remove-order-detail/<detail_id>', remove_order_detail, name='remove-order-detail'),
    path('request', send_request, name='request'),
    path('verify/<order_id>', verify, name='verify'),
]

products_order/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
from eshop_products.models import *


class Order(models.Model):
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    is_paid = models.BooleanField(verbose_name='پرداخت شده / نشده')
    payment_date = models.DateTimeField(blank=True, null=True, verbose_name='تاریخ پرداخت')
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.owner.username

    def get_total_price(self):
        amount = 0
        for detail in self.orderdetail_set.all():
            amount += detail.price * detail.count
        return amount


class OrderDetail(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE, verbose_name='سبد خرید')
    product = models.ForeignKey(ProductsList, on_delete=models.CASCADE, verbose_name='محصول')
    price = models.IntegerField(verbose_name='قیمت محصول')
    count = models.IntegerField(verbose_name='تعداد')
    date = models.DateTimeField(auto_now_add=True)

    def get_detail_sum(self):
        return self.count * self.price

    def __str__(self):
        return self.product.title

products_order/forms.py
from django import forms
from django.contrib.auth.models import User
from django.core import validators


class UserNewOrderForm(forms.Form):
    product_id = forms.IntegerField(
        widget=forms.HiddenInput(),
    )

    count = forms.IntegerField(
        widget=forms.NumberInput(),
        initial=1
    )

products_order/views.py
from datetime import time
from multiprocessing.connection import Client
from django.contrib.auth.decorators import login_required
from django.http import Http404, HttpResponse
from django.shortcuts import render, redirect
from .forms import UserNewOrderForm
from .models import OrderDetail, Order
from eshop_products.models import *
from django.shortcuts import redirect
import requests
import json
from zeep import Client


# Create your views here.
@login_required(login_url='/login')
def add_user_order(request):
    new_order_form = UserNewOrderForm(request.POST or None)

    if new_order_form.is_valid():
        order = Order.objects.filter(owner_id=request.user.id, is_paid=False).first()
        if order is None:
            order = Order.objects.create(owner_id=request.user.id, is_paid=False)

        product_id = new_order_form.cleaned_data.get('product_id')
        count = new_order_form.cleaned_data.get('count')
        if count < 0:
            count = 1
        product = ProductsList.objects.get_by_id(product_id=product_id)
        order.orderdetail_set.create(product_id=product_id, price=product.price, count=count)

        return redirect(f'/products/{product.id}/{product.title.replace(" ", "-")}')

    return redirect('/')


@login_required(login_url='/login')
def user_open_order(request, *args, **kwargs):
    context = {
        'order': None,
        'details': None,
        'total': 0
    }

    open_order: Order = Order.objects.filter(owner_id=request.user.id, is_paid=False).first()
    if open_order is not None:
        context['order'] = open_order
        context['details'] = open_order.orderdetail_set.all()
        context['total'] = open_order.get_total_price()

    return render(request, 'order/user_open_order.html', context)


@login_required(login_url='/login')
def remove_order_detail(request, *args, **kwargs):
    detail_id = kwargs.get('detail_id')
    if detail_id is not None:
        order_detail = OrderDetail.objects.get_queryset().get(id=detail_id, order__owner_id=request.user.id)
        if order_detail is not None:
            order_detail.delete()
            return redirect('user-order:user_open_order')
    raise Http404()


MERCHANT = 'XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX'
amount = 1000  # Toman / Required
description = "توضیحات مربوط به تراکنش را در این قسمت وارد کنید"  # Required
email = 'email@example.com'  # Optional
mobile = '09123456789'  # Optional

client = Client('https://www.zarinpal.com/pg/services/WebGate/wsdl')
CallbackURL = 'http://localhost:8000/verify/'  # Important: need to edit for realy server.


def send_request(request, *args, **kwargs):
    total_price = 0
    open_order: Order = Order.objects.filter(is_paid=False, owner_id=request.user.id).first()
    if open_order is not None:
        total_price = open_order.get_total_price()
        result = client.service.PaymentRequest(MERCHANT, total_price, description, email, mobile,
                                               f"{CallbackURL}/{open_order.id}")
        if result.Status == 100:
            return redirect('https://www.zarinpal.com/pg/StartPay/' + str(result.Authority))
        else:
            return HttpResponse('Error code: ' + str(result.Status))
    raise Http404()


def verify(request, *args, **kwargs):
    order_id = kwargs['order_id']
    if request.GET.get('Status') == 'OK':
        result = client.service.PaymentVerification(MERCHANT, request.GET['Authority'], amount)
        if result.Status == 100:
            user_order = Order.objects.get_queryset().get(id=order_id)
            user_order.is_paid = True
            user_order.payment_date = time.time()
            user_order.save()
            return HttpResponse('Transaction success.\nRefID: ' + str(result.RefID))
        elif result.Status == 101:
            return HttpResponse('Transaction submitted : ' + str(result.Status))
        else:
            return HttpResponse('Transaction failed.\nStatus: ' + str(result.Status))
    else:
        return HttpResponse('Transaction failed or canceled by user')

products_order/templates/order/user_open_order.html
{% extends 'base/base.html' %}
{% load static %}

{% block content %}
<div class="section">

    <!-- Breadcrumb Area Start -->
    <div class="breadcrumb-area bg-light">
        <div class="container-fluid">
            <div class="breadcrumb-content text-center">
                <h1 class="title">Shopping Cart</h1>
                <ul>
                    <li>
                        <a href="index.html">Home </a>
                    </li>
                    <li class="active"> Shopping Cart</li>
                </ul>
            </div>
        </div>
    </div>
    <!-- Breadcrumb Area End -->

</div>
<div class="section section-margin">
    <div class="container">

        <div class="row">
            <div class="col-12">

                <!-- Cart Table Start -->
                {% if order != None and details|length > 0 %}
                <div class="cart-table table-responsive">
                    <table class="table table-bordered">

                        <!-- Table Head Start -->
                        <thead>
                        <tr>
                            <th class="pro-thumbnail">Image</th>
                            <th class="pro-title">Product</th>
                            <th class="pro-price">Price</th>
                            <th class="pro-quantity">Quantity</th>
                            <th class="pro-subtotal">Total</th>
                            <th class="pro-remove">Remove</th>
                        </tr>
                        </thead>
                        <!-- Table Head End -->

                        <!-- Table Body Start -->
                        <tbody>
                        {% for detail in details %}
                        <tr>
                            <td class="pro-thumbnail"><a href="{{ detail.product.get_absolute_url }}"><img
                                    class="img-fluid"
                                    src="{{detail.product.image.url }}"
                                    alt="Product"></a></td>
                            <td class="pro-title"><a href="{{ detail.product.get_absolute_url }}">
                                {{detail.product.title }}<br></a></td>
                            <td class="pro-price"><span>${{ detail.product.price }}</span></td>
                            <td class="pro-quantity">
                                <div class="quantity">
                                    {{ detail.count }}
                                </div>
                            </td>
                            <td class="pro-subtotal"><span>${{ detail.get_detail_sum }}</span></td>
                            <td class="pro-remove"><a href="/remove-order-detail/{{ detail.id }}"><i
                                    class="pe-7s-trash"></i></a></td>
                        </tr>
                        {% endfor %}
                        </tbody>
                        <!-- Table Body End -->

                    </table>
                </div>
                {% else %}
                <div class="alert alert-warning">
                    <p>
                        Nothing In Your Buying List
                    </p>
                </div>
                {% endif %}
                <!-- Cart Table End -->

                <!-- Cart Update Option Start -->
                <div class="cart-update-option d-block d-md-flex justify-content-between">


                </div>
                <!-- Cart Update Option End -->

            </div>
        </div>

        <div class="row">
            <div class="col-lg-5 ms-auto col-custom">

                <!-- Cart Calculation Area Start -->
                <div class="cart-calculator-wrapper">

                    <!-- Cart Calculate Items Start -->
                    <div class="cart-calculate-items">

                        <!-- Cart Calculate Items Title Start -->
                        <h3 class="title">Cart Totals</h3>
                        <!-- Cart Calculate Items Title End -->

                        <!-- Responsive Table Start -->
                        <div class="table-responsive">
                            <table class="table">
                                <tbody>
                                {% for product in details %}
                                <tr>
                                    <td>{{ product.product.title }}  </td>
                                    <td>X{{ product.count }}</td>
                                </tr>
                                {% endfor %}
                                <tr class="total">
                                    <td>Total</td>
                                    <td class="total-amount">${{ total }}</td>
                                </tr>
                                </tbody>
                            </table>
                        </div>
                        <!-- Responsive Table End -->

                    </div>
                    <!-- Cart Calculate Items End -->

                    <!-- Cart Checktout Button Start -->
                    <a href="{% url 'user-order:request' %}" class="btn btn-dark btn-hover-primary rounded-0 w-100">Proceed To
                        Checkout</a>
                    <!-- Cart Checktout Button End -->

                </div>
                <!-- Cart Calculation Area End -->

            </div>
        </div>

    </div>
</div>
{% endblock  %}