account/urls.py
from django.contrib.auth import views
from django.urls import path
from .views import ProductList, ProductGallery, ProductCreator, ProductCreatorGallery, ProductCreatorUpdate, \
    ProductCreatorGalleryUpdate, ProductDeleteView, ProductGalleryDeleteView, user_register, Profile

app_name = 'account'
urlpatterns = [
    path('login/', views.LoginView.as_view(), name='login'),
    path('register/', user_register, name='register'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('profile/', Profile.as_view(), name="profile"),
    #
    # path('password_change/', views.PasswordChangeView.as_view(), name='password_change'),
    # path('password_change/done/', views.PasswordChangeDoneView.as_view(), name='password_change_done'),
    #
    # path('password_reset/', views.PasswordResetView.as_view(), name='password_reset'),
    # path('password_reset/done/', views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    # path('reset/<uidb64>/<token>/', views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    # path('reset/done/', views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]
urlpatterns += [
    path('', ProductList.as_view(), name='home'),
    path('gallery/', ProductGallery.as_view(), name='gallery'),
    path('product/create', ProductCreator.as_view(), name='productcreator'),
    path('product/create/<int:pk>', ProductCreatorUpdate.as_view(), name='productupdate'),
    path('product/create/gallery', ProductCreatorGallery.as_view(), name='productcreatorgallery'),
    path('product/create/gallery/<int:pk>', ProductCreatorGalleryUpdate.as_view(), name='productgalleryupdate'),
    path('product/delete/<int:pk>', ProductDeleteView.as_view(), name='productdelete'),
    path('product/delete/gallery/<int:pk>', ProductGalleryDeleteView.as_view(), name='productgallerydelete'),
]

djangoecommerce/urls.py
from django.conf.urls.static import static

from djangoecommerce import settings
from django.contrib import admin
from django.urls import path, include, re_path


urlpatterns = [
    path('', include('eshop_home.urls')),
    path('', include('eshop_products.urls')),
    path('', include('eshop_settings.urls')),
    path('', include('products_order.urls')),
    path('comment/', include('comment.urls')),
    re_path(r'^ratings/', include('star_ratings.urls', namespace='ratings')),
    path('account/', include('account.urls')),
    path('admin/', admin.site.urls),

]

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

eshop_products/urls.py
from django.urls import path, re_path
from eshop_products import views

app_name = 'eshop_products'
urlpatterns = [
    path('products/', views.products_list, name='products_list'),
    path('products/category/<slug:slug>/', views.products_list, name='products_list'),
    path('products/tag/<slug:slug>/', views.product_tag, name='products_tag'),
    path('products/<productId>/<name>/', views.products_detail, name='products_detail'),
    path('products/preview/<int:pk>', views.products_preview, name='products_preview'),
    path('search', views.SearchProductsView.as_view(), name='products-search'),
]

eshop_products/models.py
import os.path
from django.urls import reverse
from account.models import User
from django.db import models
from django.db.models import Q
from autoslug import AutoSlugField
from django.contrib.contenttypes.fields import GenericRelation
from comment.models import Comment
import eshop_categories.models
from eshop_categories.models import ProductsCategory
from eshop_tags.models import Tag
import django_filters


# Create your models here.

def get_filename_ext(filepath):
    base_name = os.path.basename(filepath)
    name, ext = os.path.splitext(base_name)
    return name, ext


def upload_image_path(instance, filename):
    name, ext = get_filename_ext(filename)
    final_name = f"{instance.id}-{instance.title}{ext}"
    return f"products/{final_name}"


def upload_gallery_image_path(instance, filename):
    name, ext = get_filename_ext(filename)
    final_name = f"{instance.id}-{instance.title}{ext}"
    return f"products/galleries/{final_name}"


class ProductsManager(models.Manager):
    def get_by_id(self, product_id):
        qs = self.get_queryset().filter(id=product_id)
        if qs.count() == 1:
            return qs.first()
        else:
            return None

    def get_active_products(self):
        return self.get_queryset().filter(active=True)

    def get_products_by_tag(self, tag_name):
        return self.get_queryset().filter(tag_name_iexact=tag_name, active=True)

    def search(self, query):
        lookup = (
                Q(title__icontains=query) |
                Q(description__icontains=query)
        )
        return self.get_queryset().filter(lookup, status='p').distinct()


class IPAddress(models.Model):
    ip_address = models.GenericIPAddressField()


class ProductsList(models.Model):
    STATUS_CHOICES = (
        ('d', 'پیش‌نویس'),  # draft
        ('p', "منتشر شده"),  # publish
        ('i', "در حال بررسی"),  # investigation
        ('b', "برگشت داده شده"),  # back
    )
    status = models.CharField(max_length=1, choices=STATUS_CHOICES)
    user = models.ForeignKey(User, null=True, on_delete=models.SET_NULL)
    title = models.CharField(max_length=150)
    slug = AutoSlugField(populate_from='title')
    description = models.TextField()
    full_info_description = models.TextField(null=True, blank=True, default=0)
    price = models.IntegerField()
    discount = models.IntegerField(null=True, blank=True, )
    image = models.ImageField(upload_to=upload_image_path, null=True, blank=True)
    active = models.BooleanField(default=False, verbose_name='فعال / غیرفعال')
    categories = models.ManyToManyField(ProductsCategory, related_name='products', blank=True)
    tag = models.ManyToManyField(Tag, blank=True, related_name='products')
    visit_count = models.IntegerField(default=0)
    Weight = models.CharField(max_length=200, default='')
    Materials = models.CharField(max_length=200, default='')
    Dimensions = models.CharField(max_length=200, default='')
    Other_Info = models.CharField(max_length=200, default='')
    is_especial = models.BooleanField(default=False, null=True, blank=True)
    offer = models.BooleanField(default=False, null=True, blank=True)
    our_suggestion = models.BooleanField(default=False, null=True, blank=True)
    time = models.DateTimeField(auto_now_add=True)
    # the field name should be comments
    comments = GenericRelation(Comment)
    hits = models.ManyToManyField(IPAddress, through="ProductHit", blank=True, related_name='hits')
    crated = models.DateTimeField(auto_now_add=True)
    objects = ProductsManager()

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return f"/products/{self.id}/{self.title.replace(' ', '-')}"


class ProductFilter(django_filters.FilterSet):
    class Meta:
        model = ProductsList
        fields = ['price']


class ProductHit(models.Model):
    product = models.ForeignKey(ProductsList, on_delete=models.CASCADE)
    ip_address = models.ForeignKey(IPAddress, on_delete=models.CASCADE)
    crated = models.DateTimeField(auto_now_add=True)


class ProductsGallery(models.Model):
    STATUS_CHOICES = (
        ('d', 'پیش‌نویس'),  # draft
        ('p', "منتشر شده"),  # publish
        ('i', "در حال بررسی"),  # investigation
        ('b', "برگشت داده شده"),  # back
    )
    status = models.CharField(max_length=1, choices=STATUS_CHOICES)
    user = models.ForeignKey(User, null=True, on_delete=models.SET_NULL)
    title = models.CharField(max_length=150, verbose_name='عنوان')
    image = models.ImageField(upload_to=upload_gallery_image_path, verbose_name='تصویر')
    product = models.ForeignKey(ProductsList, on_delete=models.CASCADE, verbose_name='محصول')

    def __str__(self):
        return self.title

eshop_products/forms.py
from django import forms


class CommentForm(forms.Form):
    name = forms.CharField(max_length=100)
    email = forms.EmailField(max_length=256)
    message = forms.CharField(widget=forms.Textarea)

eshop_products/views.py
import django_filters
from django.core.paginator import Paginator
from django.http import Http404
from django.shortcuts import render, redirect
from eshop_products import models
from eshop_products import forms
from eshop_categories.models import ProductsCategory
from django.shortcuts import render, get_object_or_404
from django.views.generic import ListView, DetailView, UpdateView, DeleteView
from account.mixins import AuthorAccessProductMixin
from django.contrib.auth.decorators import login_required
from eshop_tags.models import Tag
from django.db.models import Count


# Create your views here.
from products_order.forms import UserNewOrderForm


def products_list(request, slug=None):
    products = models.ProductsList.objects.all()[:9]
    paginator = Paginator(products, 9)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    categories = ProductsCategory.objects.filter(is_sub=False)
    if slug:
        category = get_object_or_404(ProductsCategory, slug=slug)
        products = models.ProductsList.objects.filter(categories=category)
    tag = Tag.objects.all()
    filter = models.ProductFilter(request.GET, queryset=models.ProductsList.objects.all())
    latest_products = models.ProductsList.objects.order_by('-id').all()[:3]
    context = {
        'products': products,
        'categories': categories,
        'tag': tag,
        'page_obj': page_obj,
        'filter': filter,
        'latest_products': latest_products,
    }

    return render(request, 'products_list/products_list.html', context)


def product_tag(request, slug):
    products = models.ProductsList.objects.all()
    tag = Tag.objects.all()
    if slug:
        tags = get_object_or_404(Tag, slug=slug)
        products = models.ProductsList.objects.filter(tag=tags)
    categories = ProductsCategory.objects.filter(is_sub=False)
    context = {
        'tag': tag,
        'products': products,
        'categories': categories,
    }
    return render(request, 'products_list/products_list.html', context)


def products_detail(request, *args, **kwargs):
    selected_product_id = kwargs['productId']
    new_order_form = UserNewOrderForm(request.POST or None, initial={'product_id': selected_product_id})
    product: models.ProductsList = models.ProductsList.objects.get_by_id(selected_product_id)
    product_gallery = models.ProductsGallery.objects.filter(product_id=selected_product_id)
    related_products = models.ProductsList.objects.get_queryset().filter(categories__products=product).distinct()
    ip_address = request.user.ip_address
    if ip_address not in product.hits.all():
        product.hits.add(ip_address)

    context = {
        'product': product,
        'gallery': product_gallery,
        'related_products': related_products,
        'new_order_form': new_order_form,
    }
    return render(request, 'products_detail/products_detail.html', context)


@login_required
def products_preview(request, pk):
    if request.user.is_superuser or request.user.is_author:
        product: models.ProductsList = models.ProductsList.objects.get(pk=pk)
        product_gallery = models.ProductsGallery.objects.filter(pk=pk)
        context = {
            'product': product,
            'gallery': product_gallery,
        }
        return render(request, 'products_detail/product_preview.html', context)
    else:
        raise Http404('Not For You')


class SearchProductsView(ListView):
    template_name = 'products_list/products_list.html'
    paginate_by = 9
    context_object_name = 'products'

    def get_queryset(self):
        request = self.request
        query = request.GET.get('q')
        if query is not None:
            return models.ProductsList.objects.search(query)

        return models.ProductsList.objects.all()

eshop_products/templates/products_list/products_list.html
{% extends 'base/base.html' %}
{% load static %}
{% load ratings %}

{% block content %}
<div class="section">

    <!-- Breadcrumb Area Start -->
    <div class="breadcrumb-area bg-light">
        <div class="container-fluid">
            <div class="breadcrumb-content text-center">
                <h1 class="title">Shop</h1>
                <ul>
                    <li>
                        <a href="index.html">Home </a>
                    </li>
                    <li class="active"> shop</li>
                </ul>
            </div>
        </div>
    </div>
    <!-- Breadcrumb Area End -->

</div>
<div class="section section-margin">
    <div class="container">
        <div class="row">
            <div class="col-lg-9 col-12 col-custom">

                <!--shop toolbar start-->
                <div class="shop_toolbar_wrapper flex-column flex-md-row mb-10">

                    <!-- Shop Top Bar Left start -->
                    <div class="shop-top-bar-left mb-md-0 mb-2">
                        <div class="shop-top-show">
                            <span>Showing 1–{{products.count}} of {{products.count}} results</span>
                        </div>
                    </div>
                    <!-- Shop Top Bar Left end -->

                    <!-- Shopt Top Bar Right Start -->
                    <div class="shop-top-bar-right">

                        <div class="shop_toolbar_btn">
                            <button data-role="grid_3" type="button" class="active btn-grid-4" title="Grid"><i
                                    class="fa fa-th"></i></button>
                            <button data-role="grid_list" type="button" class="btn-list" title="List"><i
                                    class="fa fa-th-list"></i></button>
                        </div>
                    </div>
                    <!-- Shopt Top Bar Right End -->

                </div>
                <!--shop toolbar end-->

                <!-- Shop Wrapper Start -->
                <div class="row shop_wrapper grid_3">

                    <!-- Single Product Start -->
                    {% for product in products %}
                    {% if product.status == 'p' %}
                    <div class="col-lg-4 col-md-4 col-sm-6 product aos-init aos-animate" data-aos="fade-up"
                         data-aos-delay="200">
                        <div class="product-inner">
                            <div class="thumb">
                                <a href="{{ product.get_absolute_url }}" class="image">
                                    <img class="first-image"
                                         src="{{ product.image.url }}"
                                         alt="Product">
                                    <img class="second-image" src="{{ product.image.url }}"
                                         alt="Product">
                                </a>
                            </div>
                            <div class="content">
                                <h4 class="sub-title"><a href="{{product.get_absolute_url}}">Studio Design</a>
                                </h4>
                                <h5 class="title"><a href="{{ product.get_absolute_url }}">{{ product.title }}</a></h5>

                                {% ratings product %}
                                </span>
                                <p>{{ product.description | striptags}}</p>
                                <span class="price">
                                            <span class="new">${{ product.price }}</span>
                                    <!--                                    <span class="old">$42.85</span>-->
                                    </span>
                                <div class="shop-list-btn">
                                    <!--                                    <a title="Wishlist" href="#"-->
                                    <!--                                       class="btn btn-sm btn-outline-dark btn-hover-primary wishlist"><i-->
                                    <!--                                            class="fa fa-heart"></i></a>-->
                                    <button class="btn btn-sm btn-outline-dark btn-hover-primary"
                                    ><a href="{{ product.get_absolute_url }}">See More</a>
                                    </button>

                                    <!--                                    <a title="Compare" href="#"-->
                                    <!--                                       class="btn btn-sm btn-outline-dark btn-hover-primary compare"><i-->
                                    <!--                                            class="fa fa-random"></i></a>-->
                                </div>
                            </div>
                        </div>
                    </div>
                    {% endif %}
                    {% endfor %}
                    <!-- Single Product End -->

                </div>
                <!-- Shop Wrapper End -->

                <!--shop toolbar start-->
                <div class="shop_toolbar_wrapper mt-10">

                    <!-- Shop Top Bar Left start -->

                    <!-- Shop Top Bar Left end -->

                    <!-- Shopt Top Bar Right Start -->
                    <div class="shop-top-bar-right">
                        <nav>
                            <ul class="pagination">
                                <li class="page-item disabled">
                                    {% if page_obj.has_previous %}
                                    <a class="btn btn-primary" href="?page=1">&laquo; first</a>
                                    <a href="?page={{ page_obj.previous_page_number }}"
                                       class="btn btn-primary">previous</a>
                                    {% endif %}

                                    <span class="current btn btn-primary">
                                    Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
                                    </span>

                                    {% if page_obj.has_next %}
                                    <a href="?page={{ page_obj.next_page_number }}" class="btn btn-primary">next</a>
                                    <a href="?page={{ page_obj.paginator.num_pages }}" class="btn btn-primary">last
                                        &raquo;</a>
                                    {% endif %}
                                </li>
                            </ul>
                        </nav>
                    </div>
                    <!-- Shopt Top Bar Right End -->

                </div>
                <!--shop toolbar end-->

            </div>
            <div class="col-lg-3 col-12 col-custom">
                <!-- Sidebar Widget Start -->
                <aside class="sidebar_widget mt-10 mt-lg-0">
                    <div class="widget_inner aos-init aos-animate" data-aos="fade-up" data-aos-delay="200">
                        <div class="widget-list mb-10">
                            <form class="header__search-form" action="/search" method="get">
                                <h3 class="widget-title mb-4">Search</h3>
                                <div class="search-box">
                                    <input type="search" class="form-control" placeholder="Search Our Store"
                                           aria-label="Search Our Store"
                                           value="{{ request.q }}" name="q">
                                    <button class="btn btn-dark btn-hover-primary" type="submit">
                                        <i class="fa fa-search"></i>
                                    </button>
                                </div>
                            </form>
                        </div>
                        <div class="widget-list mb-10">
                            <h3 class="widget-title mb-4">Menu Categories</h3>
                            <!-- Widget Menu Start -->
                            <nav>
                                <ul class="category-menu mb-n3">
                                    {% for category in categories %}

                                    <li class="menu-item-has-children pb-4">
                                        <a href="#">{{ category.name }} <i class="fa fa-angle-down"></i></a>
                                        <ul class="dropdown" style="display: none;">
                                            {% for sub in category.children.all %}
                                            <li><a href="{{ sub.get_absolute_url }}">{{ sub.name }}</a></li>
                                            {% endfor %}
                                        </ul>
                                    </li>
                                    {% endfor %}

                                    </li>
                                </ul>
                            </nav>
                            <!-- Widget Menu End -->
                        </div>
                        <div class="widget-list mb-10">
                            <h3 class="widget-title mb-5">Price Filter</h3>
                            <!-- Widget Menu Start -->
                            <form action="#">
                                <div id="slider-range"
                                     class="ui-slider ui-corner-all ui-slider-horizontal ui-widget ui-widget-content">
                                    <div class="ui-slider-range ui-corner-all ui-widget-header"
                                         style="left: 0%; width: 100%;"></div>
                                    <span tabindex="0" class="ui-slider-handle ui-corner-all ui-state-default"
                                          style="left: 0%;"></span><span tabindex="0"
                                                                         class="ui-slider-handle ui-corner-all ui-state-default"
                                                                         style="left: 100%;"></span></div>
                                <button class="slider-range-submit" type="submit">Filter</button>
                                <input class="slider-range-amount" type="text" name="text" id="amount">
                            </form>
                            <!-- Widget Menu End -->
                        </div>
                        <div class="widget-list mb-10">
                            <h3 class="widget-title mb-4">Color</h3>
                            <div class="sidebar-body">
                                <ul class="tags mb-n2">
                                    {% for color in tag %}
                                    {% if color.is_color%}
                                    <li><a href=" {% url 'eshop_products:products_tag' color.slug %} ">
                                        {{ color.title }}</a>
                                    </li>
                                    {% endif %}
                                    {% endfor %}
                                </ul>
                            </div>
                        </div>
                        <div class="widget-list mb-10">
                            <h3 class="widget-title mb-4">Tags</h3>
                            <div class="sidebar-body">
                                <ul class="tags mb-n2">
                                    {% for tag in tag %}
                                    <li><a href=" {% url 'eshop_products:products_tag' tag.slug %} ">{{tag.title}}</a>
                                    </li>
                                    {% endfor %}
                                </ul>
                            </div>
                        </div>
                        <div class="widget-list">
                            <h3 class="widget-title mb-4">Recent Products</h3>
                            <div class="sidebar-body product-list-wrapper mb-n6">
                                <!-- Single Product List Start -->
                                {% for product in latest_products%}
                                <div class="single-product-list product-hover mb-6">
                                    <div class="thumb">
                                        <a href="{{ product.get_absolute_url }}" class="image">
                                            <img class="first-image"
                                                 src="{{ product.image.url }}" alt="Product">
                                            <img class="second-image"
                                                 src="{{ product.image.url }}" alt="Product">
                                        </a>
                                    </div>
                                    <div class="content">
                                        <h5 class="title"><a href="{{ product.get_absolute_url }}">
                                            {{ product.title}}</a>
                                        </h5>
                                        <span class="price">
													<span class="new">${{ product.price }}</span>
                                            <!--                                            <span class="old">$42.50</span>-->
                                            </span>
                                    </div>
                                </div>
                                {% endfor %}
                                <!-- Single Product List End -->


                            </div>
                        </div>
                    </div>
                </aside>
                <!-- Sidebar Widget End -->
            </div>
        </div>
    </div>
</div>
{% endblock %}